### PR TITLE
DON'T MERGE - SHOWS BUG: directly_contains doesn't let you create relationships in memory and doesn't work with anything but Files

### PR DESCRIPTION
**Pull request by flyingzumwalt**
ref #857

3 tests to show what happens when you
1. try to directly contain an ActiveFedora::Base instead of an ActiveFedora::File
2. try to add directly_contained objects in memory (add to a parent object that hasn't been saved yet)

### CODE REVIEW

**Comment by flyingzumwalt** [comment]
@elrayle @jcoyne Clearer examples of the problems with directly_contains that are forcing downstream tests to always create/save instead of testing in memory.

**Comment by terrellt** [comment]
@jcoyne I'm looking at this ticket now and the major issue seems to be that you have to assign an ID at creation. Maybe AF::Base objects should have flexible IDs until they're persisted?

**Comment by jcoyne** [comment]
@terrellt yes, the current solution was an expedient way to get it done, but certainly not the best way.  It probably just needs to get set up with an autosave.

**Comment by mjgiarlo** [comment]
@terrellt Does this PR still need attention?

**Comment by terrellt** [comment]
@mjgiarlo Yup, still broken.

**Comment by grosscol** [comment]
Just ran into this one again as I'm trying to refactor the specs to avoid calling .save when possible.  Manually assigning an id when creating an object doesn't alleviate the situation.

**Comment by jrgriffiniii** [comment]
I am closing this due to the age of this pull request.

**Pull request closed without merging**
